language: php

php:
- 7.1
- 7.2
- 7.3
- 7.4

env:
    matrix:
    #- COMPOSER_FLAGS="--prefer-lowest" # Disabled until works w/7.4 (2019-12-04)
    - COMPOSER_FLAGS=""

services:
- mysql
- postgresql

sudo: required

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- mysql -e 'CREATE DATABASE forge;'
- psql -c 'CREATE DATABASE forge;' -U postgres
- psql -c 'CREATE ROLE root SUPERUSER LOGIN;' -U postgres

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --configuration phpunit.xml.travis

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
